### ISSUE TITLE
Link to jsCoq SF version

### ISSUE THREAD

**Issue by ejgallego** [clarksmr/sf-lectures#1]
Dear Michael, I saw your videos on Youtube and they are great.

I'm opening this issue just to point out (I tried on Youtube but can't paste links in the comments) that jsCoq has a full interactive version of SF, which could be useful in the class. Try it here: https://coq.vercel.app/ext/sf/

Kind regards,
Emilio

**Comment by clarksmr** [comment]
Thanks!  I'm aware of jsCoq and already demoed the scratchpad [in an early video](https://youtu.be/QOdRXlFdd5Q) and mentioned it in my [installation instructions](https://github.com/clarksmr/sf-lectures/blob/main/install.md).  It is great to have available, and that's why I featured it.

However I am using a specific version of both Coq and SF (customized, in fact) in these videos.  Those will be inconsistent w.r.t. the URL you mention — if not already now, then certainly going forward.  That is why I have provided my own repo with the textbook files and notes.
